#server:
#  port: 19022
#
#spring:
#  application:
#    name: auth
#  data:
#    redis:
#      host: redis
#      port: 6379
#      password:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#
#jwt:
#  secret: ${JWT_SECRET_KEY}
#  access-expiration: ${JWT_ACCESS_EXPIRATION}
#  refresh-expiration: ${JWT_REFRESH_EXPIRATION}


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:18999/eureka/
#  instance:
#    prefer-ip-address: true
