server:
  port: 19099


spring:
  application:
    name: user-service


  datasource:
    url: jdbc:mysql://${Mysql_host}:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${Mysql_name}
    password: ${Mysql_password}


  sql:
    init:
      mode: always


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true


  data:
    redis:
      host: ${Redis_host}
      port: 6379
      username: ${Redis_name}
      password: ${Redis_password}


  kafka:
    host: ${Kafka_host}
    bootstrap-servers: ${Kafka_host}:9092
    username: ${Kafka_name}
    password: ${Kafka_password}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://${Eureka_name}:${Eureka_password}@${Eureka_host}:19090/eureka/
#  instance:
#    hostname: ${My_host}
#    securePortEnabled: true
#    nonSecurePortEnabled: false
#    securePort: 443
#    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
#    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
#    homePageUrl: https://${eureka.instance.hostname}/
#    preferIpAddress: false
#    secureVirtualHostName: ${spring.application.name}


jwt:
  secret:
    key: ${Jwt_secret_key}
