management:
  tags:
    clientName: client.name
    http.method: method
    http.status_code: status
    http.url: uri
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19042

NAVER:
  ID: ${NAVER_Client_ID}
  KEY: ${NAVER_Secret_KEY}
  URL: ${NAVER_URL}

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-hub-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-hub-service