##server:
##  port: 19021
#
#spring:
#  application:
#    name: user
#  datasource:
#    url: jdbc:postgresql://localhost:5432/users
#    username: sa
#    password: sa
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#
#eureka:
#  client:
#    register-with-eureka: true  # Eureka Server에 등록
#    fetch-registry: true  # Eureka Server에서 서비스 목록 가져오기
#    service-url:
#      defaultZone: http://localhost:18999/eureka/
#  instance:
#    prefer-ip-address: true  # 서비스 등록 시 IP 주소 사용
