#spring:
#  config:
#    import: optional:file:.env[.properties]
#  application:
#    name: slack
#  datasource:
#    url: jdbc:postgresql://localhost:5432/slack
#    username: sa
#    password: sa
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 30
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: systempass
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:18999/eureka/
#
#
#management:
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
#  tracing:
#    sampling:
#      probability: 1.0
#
#server:
#  port: 19041
#
#slack:
#  key: ${SLACK_KEY}
#
#ai:
#  api:
#    key: ${AI_API_KEY}
#    url: ${AI_API_URL}
#
#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /docs
#    url: /springdoc/openapi3-slack-service.json
#    operations-sorter: method
#    tags-sorter: alpha
#  api-docs:
#    enabled: true
#    path: /api-docs-slack-service
