management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 19030

springdoc:
  swagger-ui:
    enabled: true
    path: /docs
    url: /springdoc/openapi3-company-service.json
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs-company-service