#global:
#  scrape_interval: 15s
scrape_configs:
  - job_name: 'monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:19090']
    basic_auth:
      username: "admin"
      password: "password"