spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/takeoff-26/logistics-service.git
          default-label: dev
          search-paths: config/configures/**

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18999/eureka/
