spring:
  data:
    redis:
      host: 192.168.0.16
      port: 6379
      username : default
      password : systempass

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

  sql:
    init:
      mode: always